### ISSUE TITLE
crane: ERROR: Job failed (system failure): Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown (exec.go:57:0s)

### ISSUE THREAD

**Issue by AndrewCharlesHay** [google/go-containerregistry#1503]
### Describe the bug

I have the following step in Gitlab CI. Referenced [here](https://github.com/google/go-containerregistry/tree/main/cmd/crane#using-with-gitlab) 

```yaml
.push_nexus:
  stage: push
  extends:
    - .get_env_vars
    - .post_env_vars
  image:
    name: gcr.io/go-containerregistry/crane:47f093330862ba6982f644003621eddc9e7dc36e
    entrypoint: [""]
  script:
    - crane auth login -u "$NEXUS_GITLAB_USER" -p "$NEXUS_GITLAB_PASSWORD" $NEXUS_DOCKER_PUSH;
    - crane push benchmark-image.tar $DOCKER_IMAGE
```

and get the following error:

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/19394493/206040727-8eb4fc32-7a89-40ff-b677-778d77bc5aef.png">

### Expected behavior

A push of the tar

- Output of `crane version`
- Registry used: GCR to pull crane, ECR to push image
