### ISSUE TITLE
question: How to authenticate to AWS ECR using crane ?

### ISSUE THREAD

**Issue by Snoobz** [google/go-containerregistry#1755]
Hello,

I would like to use crane to push either into the Gitlab registry or in Amazon ECR, using a Gitlab CI pipeline.

I can perfectly push to the Gitlab registry, but I can’t find a way to authenticate to AWS ECR.

Can anyone please provide an example on how to authenticate to AWS ECR using crane? I would like to use an AWS access and secret key to authenticate to the service.
I can do it just fine using Kaniko, but crane it looks less documented on how to do it.

Thanks for the help!

Regards,

**Comment by sjoukedv** [comment]
I have another CI job that does the `aws ecr get-login-password` (because the aws-cli is not available in the crane image) and pass the 'password' to the crane job where I do:

```sh
/ko-app/crane auth login -u AWS -p $ECR_REGISTRY_PASSWORD $ECR_REGISTRY
```

**Comment by Snoobz** [comment]
Hello,

Thank you for your reply, this indeed helped me quite a bit!
Any clue on what type of distribution the Crane Docker image is based on? I would like to include the "aws cli" binary inside the image (by building another image via a Dockerfile), but can't really seem to find out what's the base distribution used.

If you have any ideas, well I'll take the answer!
Thanks again for your help though regarding this first request!

**Comment by sjoukedv** [comment]
> Hello,
> 
> Thank you for your reply, this indeed helped me quite a bit!
> Any clue on what type of distribution the Crane Docker image is based on? I would like to include the "aws cli" binary inside the image (by building another image via a Dockerfile), but can't really seem to find out what's the base distribution used.
> 
> If you have any ideas, well I'll take the answer!
> Thanks again for your help though regarding this first request!

Inside the container

```sh
cat /etc/os-release
```

I believe it's based on the distroless thingy of Google containertools

**Comment by whyyouwannaknow** [comment]
> > Hello,
> > Thank you for your reply, this indeed helped me quite a bit!
> > Any clue on what type of distribution the Crane Docker image is based on? I would like to include the "aws cli" binary inside the image (by building another image via a Dockerfile), but can't really seem to find out what's the base distribution used.
> > If you have any ideas, well I'll take the answer!
> > Thanks again for your help though regarding this first request!
> 
> Inside the container
> 
> ```shell
> cat /etc/os-release
> ```
> 
> I believe it's based on the distroless thingy of Google containertools

Yeah well, the container doens't let me do a cat or ls inside of it (no /bin/sh binary apparently).
From what I've found in the #1356 installing a package inside the provided image of Crane is definitely not simple!

So yeah, like you, I did a CI job that retrieve the password for ECR and another job which authenticates and push to the registry.

Thank again for the help though.

**Comment by sjoukedv** [comment]
> > > Hello,
> > > Thank you for your reply, this indeed helped me quite a bit!
> > > Any clue on what type of distribution the Crane Docker image is based on? I would like to include the "aws cli" binary inside the image (by building another image via a Dockerfile), but can't really seem to find out what's the base distribution used.
> > > If you have any ideas, well I'll take the answer!
> > > Thanks again for your help though regarding this first request!
> > 
> > Inside the container
> > 
> > ```shell
> > cat /etc/os-release
> > ```
> > 
> > I believe it's based on the distroless thingy of Google containertools
> 
> Yeah well, the container doens't let me do a cat or ls inside of it (no /bin/sh binary apparently).
> From what I've found in the #1356 installing a package inside the provided image of Crane is definitely not simple!
> 
> So yeah, like you, I did a CI job that retrieve the password for ECR and another job which authenticates and push to the registry.
> 
> Thank again for the help though.

the `-debug` variant has a shell inside the container

**Comment by whyyouwannaknow** [comment]
> > > > Hello,
> > > > Thank you for your reply, this indeed helped me quite a bit!
> > > > Any clue on what type of distribution the Crane Docker image is based on? I would like to include the "aws cli" binary inside the image (by building another image via a Dockerfile), but can't really seem to find out what's the base distribution used.
> > > > If you have any ideas, well I'll take the answer!
> > > > Thanks again for your help though regarding this first request!
> > > 
> > > 
> > > Inside the container
> > > ```shell
> > > cat /etc/os-release
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I believe it's based on the distroless thingy of Google containertools
> > 
> > 
> > Yeah well, the container doens't let me do a cat or ls inside of it (no /bin/sh binary apparently).
> > From what I've found in the #1356 installing a package inside the provided image of Crane is definitely not simple!
> > So yeah, like you, I did a CI job that retrieve the password for ECR and another job which authenticates and push to the registry.
> > Thank again for the help though.
> 
> the `-debug` variant has a shell inside the container

That is indeed correct, but still I didn't manage to find a way to install any binaries inside it. The distribution is apparently a Debian 11 (from what I have retrieved yesterday doing a "cat /etc/*-release"), but apt-get is not a recognized command (when I do a "RUN apt-get update" in a Dockerfile).

This might be because apt-get is not in the $PATH (?), but also maybe because they removed the binary?
Of course, the "which" command doens't seem to be included into the image.

Did you managed at all to install any packages inside the Crane :debug image?

**Comment by sjoukedv** [comment]
It's based on this one https://github.com/GoogleContainerTools/distroless

Use a different base image e.g. alpine and install the tool there manually that should work

**Comment by webcane** [comment]
1-st build with kaniko
```
stages:
  - build
  - push

variables:
  APP_NAME: my_app
  IMAGE_TAG_COMMIT: $APP_NAME:$CI_COMMIT_SHORT_SHA
  ECR_REPOSITORY_URI: $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  
kaniko-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.2-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination $IMAGE_TAG_COMMIT
      --tar-path $APP_NAME.tar
      --no-push
  artifacts:
    paths:
      - $APP_NAME.tar
    when: on_success
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
```
then login to aws
```
aws-login-dev:
  stage: push
  environment: dev
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - aws --version
  script:
    - echo "Get AWS login password"
    - echo "ECR_REGISTRY_PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)" >> aws.dev.env
  artifacts:
    reports:
      dotenv: aws.dev.env
```
and push using the crane
```
crane-push-dev:
  stage: push
  environment: dev
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u AWS -p $ECR_REGISTRY_PASSWORD $ECR_REPOSITORY_URI
    - crane push $APP_NAME.tar $ECR_REPOSITORY_URI/$IMAGE_TAG_COMMIT
  needs:
    - job: aws-login-dev
      artifacts: true
    - job: kaniko-build
      artifacts: true
```
