### ISSUE TITLE
question: what is the Go version support policy?

### ISSUE THREAD

**Issue by spencerschrock** [google/go-containerregistry#2045]
The newest release (v0.20.3) includes a change from #2025 which bumps the Go directive from `1.18` to `1.23.0`.  As far as I know, the reason wasn't due to a feature required in Go 1.23, but rather "update everything to latest so that things build in CI." This change propagates to dependent libraries, so we are also required to use Go 1.23.

Would you consider walking back the 1.23 requirement if you don't need the features? Or supporting the last two versions of Go (1.22 too  in this case).

There are other ways to use the latest version of Go in your CI, without requiring it for the project:

Instead of 
```yaml
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
```

There is also an `actions/setup-go` [stable alias](https://github.com/actions/setup-go/blob/f111f3307d8850f501ac008e886eec1fd1932a34/README.md#using-stableoldstable-aliases) for the latest Go release:
```yaml
    - uses: actions/setup-go@v5
      with:
        go-version: stable

```

@imjasonh would this work for you?

edit: I see one of your dependencies requires at least `1.22.7`, so the request would be to use that instead of `1.23.0` (although `pkg/authn/k8schain/go.mod` and `pkg/authn/kubernetes/go.mod` would require 1.23.0 for theirs)
