### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davidbIQ** [google/go-containerregistry#504]
I installed skaffold on windows 10 using choco (version 35), and ran the getting-started app using skaffold dev, and it was ok.  I upgraded to version 0.37.0 and it throws this error (below).  Reverting back to 35 fixes the issue.  This is within azure, with a private repo:

```
The skaffold yaml is:
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: sandbox.azurecr.io/dave/gettingstarted
deploy:
  kubectl:
    manifests:
    - k8s-pod.yaml
```

the error thrown is:

```
[34mkubectl client version: 1.14[0m
pod/getting-started configured
[34mDeploy complete in 1.9699197s[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x13a18f2]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc00008da00, 0xc0001b8000, 0xd, 0xc0001b8000)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:276 +0x3b2
github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc00008da00, 0x0, 0x0, 0x0)
...
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x1b54e20, 0xc0000b6008, 0x1b54e20, 0xc0000b6010, 0xc00047ff88, 0x405656)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:27 +0x5f
main.main()
        /ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:30 +0x55
```
