### ISSUE TITLE
Auth broke in GitLab CI

### ISSUE THREAD

**Issue by max-wittig** [google/go-containerregistry#555]
I think the error lies on my side, but maybe you got an idea:

Using GitLab CI, I'm generating a config file, using this syntax:

```yml
test:
  image: golang:1.12.4-stretch
  script:
    - go get github.com/google/go-containerregistry/cmd/crane
    - mkdir /root/.docker && echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /root/.docker/config.json
    - crane cp $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE/test:latest
```

```bash
2019/10/01 06:33:29 fetching "myregistry.example.com/example/example-test:latest": DENIED: access forbidden
```

Now that the config file parsing was changed in cf66aa2c31a900626cc59d2747a644d7d8f05ef3, am I missing some parameter in the config or should this be enough?

Thanks for any help!
