### ISSUE TITLE
Crane broke again in GitLab CI :(

### ISSUE THREAD

**Issue by max-wittig** [google/go-containerregistry#598]
I guess one should consider the master of this repository as not stable anymore.

Maybe an issue with the `go.mod`?

> go get github.com/google/go-containerregistry/cmd/crane
cd /go/src/github.com/google/go-containerregistry; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/k8s.io/code-generator' in .gitmodules
package github.com/google/go-containerregistry/cmd/crane: exit status 128

What's the alternative? Would it be possible for you to provide an docker image, similar to `kaniko:debug` with a shell? Thanks 😃

**Comment by jonjohnsonjr** [comment]
> I guess one should consider the master of this repository as not stable anymore.

Sorry :(

I'm kind of shocked that our tests didn't catch this.

> Maybe an issue with the go.mod?

I'm guessing this was broken by https://github.com/google/go-containerregistry/pull/548/files#diff-87ee15ebb32e08fc4ef22a736ce9000d

I'll send a PR to revert that file, but I'd like to figure out how to catch this regression. I can't seem to reproduce your issue. If you have any ideas for how we'd catch this in this future, I'd gladly take a PR :smile: 

> Would it be possible for you to provide an docker image, similar to kaniko:debug with a shell?

Are you using the images we publish ([here](gcr.io/go-containerregistry/crane))? These don't seem broken, at least:

```
$ docker run gcr.io/go-containerregistry/crane digest ubuntu
2019/10/28 18:01:56 No matching credentials were found, falling back on anonymous
sha256:a7b8b7b33e44b123d7f997bd4d3d0a59fafc63e203d17efedf09ff3f6f516152
```

We could pretty easily add a `:debug` image to track `:latest`, but I'm not sure that it would help in this case? cc @ImJasonH wdyt?

**Comment by jonjohnsonjr** [comment]
@max-wittig can you describe a bit more about how this is failing for you? I don't believe we use git submodules at all, so I'm not sure where that error message is coming from.

**Comment by max-wittig** [comment]
@jonjohnsonjr Thanks for the response!

Not sure, if you're familar with GitLab CI, but we're basically just running this.

1. Spawning a new container with golang:1.12.4-stretch
2. Installing crane
3. Running a crane cp

```yml
crane-test:
  image: golang:1.12.4-stretch
  stage: crane
  script:
    - go get github.com/google/go-containerregistry/cmd/crane
    - mkdir /root/.docker && echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /root/.docker/config.json
    - crane cp $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE/copy:latest
```

An example of a failed job can be found on gitlab.com: https://gitlab.com/siemens/todo/-/jobs/336062213

Thanks for the help!
