### ISSUE TITLE
Provide crane:debug image with shell

### ISSUE THREAD

**Issue by max-wittig** [google/go-containerregistry#605]
Providing a `crane:debug` image with a working shell would enable people to directly use `crane` in GitLab CI, instead of using a golang image and installing crane into it.

Kaniko already does this and GitLab has even written a little help section about it:
https://docs.gitlab.com/ce/ci/docker/using_kaniko.html#building-a-docker-image-with-kaniko

Kaniko example:

```yml
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
```
