### ISSUE TITLE
Add Gitlab + crane example

### ISSUE THREAD

**Issue by marklagendijk** [google/go-containerregistry#671]
In #605 a debug image was added to allow for usage similar to kaniko, so that crane can be easily used from Gitlab.
However, there seems to be no documentation on how to use it with Gitlab.

**Comment by marklagendijk** [comment]
Non-verified example:
``` yaml
docker-release-tag:
  stage: docker-release-tag
  only:
    refs:
      - /^release\/.+/
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - mkdir /root/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /root/.docker/config.json
    - /ko-app/crane tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA CI_COMMIT_TAG
```
